
cd Server
godot &
cd ..
sleep 2
cd Client
MULTI_USER_TESTING=TRUE DESIREDSCREEN=1 ACTIVECORNER=1 godot &
sleep 2
MULTI_USER_TESTING=TRUE DESIREDSCREEN=1 ACTIVECORNER=2 godot &
MULTI_USER_TESTING=TRUE DESIREDSCREEN=1 ACTIVECORNER=3 godot &
MULTI_USER_TESTING=TRUE DESIREDSCREEN=1 ACTIVECORNER=4 godot &
echo "Instances started"

