# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: '**'
  pull_request:
    branches: '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "keymap protector running"
          if cmp --silent Client/project.godot Client/project.godot_prot; then
            echo "all clear"
          else
            ver1=$(grep "config/git_copy_prot" Client/project.godot | tr -d -c 0-9)
            ver2=$(grep "config/git_copy_prot" Client/project.godot_prot | tr -d -c 0-9)
            echo "main version $ver1"
            echo "alt version $ver2"
            if [[ ver1 -lt ver2 ]]; then
              cp Client/project.godot_prot Client/project.godot
              ver_master=$ver2
            else
              cp Client/project.godot Client/project.godot_prot
              ver_master=$ver1
            fi
            echo "master ver $ver_master"
            sed -i -e "s:config/git_copy_prot=.:config/git_copy_prot=$((ver_master+1)):" Client/project.godot
            sed -i -e "s:config/git_copy_prot=.:config/git_copy_prot=$((ver_master+1)):" Client/project.godot_prot
          fi
          
      - name: Push changes
        uses: actions-go/push@v1
    
    





